# Generated by Django 4.0.3 on 2022-03-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_api', '0004_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='update_stock',
            new_name='cuantity',
        ),
    ]
